/**:
  ros__parameters:
    video_device: "/dev/video0"
    framerate: 30.0
    io_method: "mmap"
    frame_id: "camera"
    pixel_format: "mjpeg2rgb"
    av_device_format: "YUV422P"
    image_width: 1280
    image_height: 720
    camera_name: "webcam"
    # camera_info_url: "package://usb_cam/config/camera_info.yaml"