/**:
  ros__parameters:

    image_transport: "raw"

    num_streams: 1

    stream0: [ "/uvc1/image_raw", "/uvc1/camera_info", "map" ]
    stream0_offset: [ 0., 0., 0.76, 0.653, -0.653, 0.271, -0.271 ]

    feature:  # detection export key: 0=off, 1=enable, -1=only when filtered
      publish_best_detection_tf: 0
      export_best_detection: 1
      export_all_detections: 0
      debug:
        publish_stream: true
        publish_individual_tag_solution_tfs: true
        publish_group_solution_tfs: true

    filtering:
      bounds_min: [ 0.2, 0.2, -0.3 ]  # minimum valid bound from which tags should be detected (world frame)
      bounds_max: [ 6.68, 5., 0.3 ]   # maximum valid bound from which tags should be detected (world frame)
      use_bounds: false
      thresh:
        min_tags_per_range: 0.6         # there must be at least this number of tags per [avg] meter of distance to the detected tags
        max_rms_per_tag: 0.40           # maximum valid RMS error per tag
        min_sum_pix_area: 7500.         # minimum total pixels that detected tags must occupy
        min_tags: 2

    aruco:
      predefined_family_idx: 20     # tag family to detect -- 20 = AprilTag 36h11
      tag_ids: [ 0., 1., 2., 3., 4., 5. ]   # the tag ids which should be used, and whose corners are defined below:

      tag0_static: false
      tag0_frames: [ "base_link" ]
      tag0_corners: [ 0.119, -0.350, 0.411,
                      0.115, -0.350, 0.577,
                      0.282, -0.350, 0.580,
                      0.285, -0.350, 0.414 ]
      tag1_static: false
      tag1_frames: [ "base_link" ]
      tag1_corners: [ 0.115, 0.350, 0.577,
                      0.119, 0.350, 0.411,
                      0.285, 0.350, 0.414,
                      0.282, 0.350, 0.580 ]
      tag4_static: false
      tag4_frames: [ "base_link" ]
      tag4_corners: [ 0.370, -0.273, 0.518,
                      0.327, -0.340, 0.518,
                      0.326, -0.340, 0.598,
                      0.369, -0.273, 0.598 ]
      tag5_static: false
      tag5_frames: [ "base_link" ]
      tag5_corners: [ 0.327, 0.340, 0.518,
                      0.370, 0.273, 0.518,
                      0.369, 0.273, 0.598,
                      0.326, 0.340, 0.598 ]
    # separate test rig >>>>>
      tag2_static: false
      tag2_frames: [ "base_link" ]
      tag2_corners: [ -0.040, 0.055, 0.045,
                       0.039, 0.055, 0.044,
                       0.040, 0.055, 0.124,
                      -0.039, 0.055, 0.125 ]
      tag3_static: false
      tag3_frames: [ "base_link" ]
      tag3_corners: [ 0.055,  0.040, 0.043,
                      0.055, -0.039, 0.042,
                      0.055, -0.040, 0.122,
                      0.055,  0.039, 0.123 ]
