/**:
    ros__parameters:
        img_topics: [ "/model/lance/left_cam/image",
                        "/model/lance/fwd_cam/image",
                        "/model/lance/rght_cam/image" ]
        info_topics: [ "/model/lance/left_cam/camera_info",
                        "/model/lance/fwd_cam/camera_info",
                        "/model/lance/rght_cam/camera_info" ]

        debug_topic: "/aruco_server/debug/image"
        debug_pub_freq: 30

        tags_frame_id: "dlo_odom"
        base_frame_id: "base_link"

        pose_pub_topic: "/aruco_server/pose"

        filtering:
            prev_transform: true
            bounding_box: true
            bounds_min: [ 0.2, 0.2, -0.4 ]
            bounds_max: [ 6.68, 5., 0.3 ]

        aruco_predefined_family_idx: 20     # AprilTag 36h11
        tag_ids: [ 0., 1., 2., 3. ]

        tag0: [ 0.216, 1.055, 0.06,
                0.216, 0.575, 0.06,
                0.216, 0.575, 0.54,
                0.216, 1.055, 0.54 ]

        tag1: [ 0.256, 0.485, 0.05,
                0.576, 0.245, 0.05,
                0.576, 0.245, 0.45,
                0.256, 0.485, 0.45 ]

        tag2: [ 0.646, 0.215, 0.03,
                0.886, 0.215, 0.03,
                0.886, 0.215, 0.27,
                0.646, 0.215, 0.27 ]

        tag3: [ 0.636, 0.215, 0.32,
                0.796, 0.215, 0.32,
                0.796, 0.215, 0.48,
                0.636, 0.215, 0.48 ]
